### ISSUE TITLE
removing make+typeof pattern 

### ISSUE THREAD

**Issue by binarytide** [typeonce-dev/effect-getting-started-course#3]
I'm learning Effect and found your course super helpful, but I see you refactored and removed the make+typeof pattern and just curious why?

**Comment by SandroMaglione** [comment]
Hi @binarytide 

Since `effect` [v3.9](https://effect.website/blog/releases/effect/39/) a new `Effect.Service` API has been added that aims to simplify the common make+typeof pattern in a single API. The course reflects the use of this API.

Did you find any issue while following the course without make+typeof? Let me know if I can update anything to make it more clear.

**Comment by binarytide** [comment]
when I went through the course I remembered seeing the make+typeof pattern and was using as a cheatsheet for my own project and when I grabbed the repo I noticed the disparity between it and the course, might've been me getting mixed up, I'm diving into the deep end with typescript and effect(I've been strictly js for years) but your course has been incredibly helpful in my journey(same with xstate, another difficult lib you've helped me move forward with) keep up the great work!

**Comment by SandroMaglione** [comment]
That's great @binarytide!

Let me know if I can help you in any other way with any clarification 👍
